### ISSUE TITLE
Simpler solution

### ISSUE THREAD

**Issue by Joshuad2uiuc** [matyus/one_plus_one#1]
https://github.com/matyus/one_plus_one/blob/520b7d61dbf8fe3f68ef7b233e7c25de294cb4d5/lib/one_plus_one.rb#L4

This can be shortened to just `2` instead of `1+1`, it is the closed form solution.

**Comment by matyus** [comment]
This library must perform the calculation. 

It wouldn't be "one plus one" unless it was actually adding one to one. 

Returning a pre-calculated value (while more efficient) defeats the purpose of this gem.
